---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app # name of the app
  namespace: argocd # dont confuse with a target namespace, it is always to be argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # if you want to delete all of them at once
spec:
  project: default # provide a logical grouping of app which is useful when argoCD is used by multiple teams
  source:
    repoURL: https://github.com/xhosro/public-repo-gitops.git # its not different if we use hhtp or ssh, but always recommended to use .git, since argocd will not follow redirections
    targetRevision: main # the head points to your main's branch's latest commit
    path: my-app
  destination: # is useful when you use a single argocd instance to deploy app to multiple clusters.
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
       prune: true
       selfHeal: true
       allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
